#!/bin/bash
#SBATCH --job-name=eigen-sweep
#SBATCH --output=./output/paramSweep/eigen-%a_%A.out
#SBATCH --time=0:10:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --array=0-7
#SBATCH --partition=cpu-preempt

# Optional: Load modules
# module load python
# conda activate hpc-s26

set -euo pipefail

# Sweep values
Ns=(10 20 30 40)
potentials=(well harmonic)

nN=${#Ns[@]}
np=${#potentials[@]}
ntasks=$((nN*np))

if [ "$SLURM_ARRAY_TASK_ID" -ge "$ntasks" ]; then
    echo "Invalid TASK_ID: $SLURM_ARRAY_TASK_ID exceeds total tasks $ntasks"
    exit 1
fi

iN=$(( SLURM_ARRAY_TASK_ID / np ))
ip=$(( SLURM_ARRAY_TASK_ID % np ))

N=${Ns[$iN]}
pot=${potentials[$ip]}

mkdir -p results

python3 src/eigen.py "$N" "$pot" 5

